---
title: "04 Automated Machine Learning with H2O (II)"
date: "2023-06-13"
output:
  html_document:
    toc: yes
    toc_float: yes
    df_print: paged
    collapsed: no
    number_sections: yes
    toc_depth: 3
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

## Load the training & test dataset

```{r}
library(tidyverse)
library(recipes)
library(rsample)

dataset <- read_csv("data04/product_backorders.csv") %>% 
  mutate(product_backorder = went_on_backorder %>% str_to_lower() %>% str_detect("yes") %>% as.numeric()) %>% select(-c(went_on_backorder))

glimpse(dataset)

split_obj<- initial_split(dataset, prop = 0.85)
train_data<- training(split_obj)
test_data<- testing(split_obj)
```

## Specifiy the response and predictor variables

```{r}
recipe_obj <- recipe(product_backorder ~., data = train_data) %>% 
    step_zv(all_predictors()) %>% 
    step_dummy(all_nominal(),-all_outcomes()) %>%
    prep()

summary(recipe_obj)

glimpse(bake(recipe_obj,new_data = NULL))
```

## run AutoML specifying the stopping criterion

```{r}
library(h2o)
h2o.init()
split_h2o <- h2o.splitFrame(as.h2o(train_data), ratios = c(0.85), seed = 52)
train_h2o <- split_h2o[[1]]
valid_h2o <- split_h2o[[2]]
test_h2o  <- as.h2o(test_data)

# Set the target and predictors
y <- "product_backorder"
x <- setdiff(names(train_h2o), y)
automl_models_h2o <- h2o.automl(
  x = x,
  y = y,
  training_frame    = train_h2o,
  validation_frame  = valid_h2o,
  leaderboard_frame = test_h2o,
  max_runtime_secs  = 140,
  nfolds            = 5,
  stopping_metric = "mae", stopping_rounds = 3,
                        stopping_tolerance = 1e-3
)
```

## View the leaderboard

```{r}
automl_models_h2o@leaderboard 
automl_models_h2o@leader

?h2o.deeplearning
extract_h2o_model_name_by_position <- function(h2o_leaderboard, n = 1, verbose = T) {
    model_name <- h2o_leaderboard %>%
        as.tibble() %>%
        slice_(n) %>%
        pull(model_id)
    if (verbose) message(model_name)
    return(model_name)
}
```

## Predicting using Leader Model

```{r}
best_model <- automl_models_h2o@leaderboard %>% 
  extract_h2o_model_name_by_position(1) %>% 
  h2o.getModel()

predictions <- h2o.predict(best_model, newdata = as.h2o(test_data))

typeof(predictions)

predictions_tbl <- predictions %>% as_tibble()

glimpse(predictions_tbl)

```

## Save the leader model

```{r}
best_model %>% h2o.saveModel(path = "data04/model")
```