project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal-Business Decisions with Machine Learning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 Machine Learning Fundamentals"
            file: content/01_journal/01_ml01_ml_fund.rmd
          - text: "02 Supervised ML - Regression"
            file: content/01_journal/02_ml02_sup_ML.rmd
          - text: "03 Automated Machine Learning with H2O (I)"
            file: content/01_journal/03_ml03_h2oI.rmd
          - text: "04 Automated Machine Learning with H2O (II)"
            file: content/01_journal/04_ml04_h2oII.rmd
          - text: "05 Performance Measures"
            file: content/01_journal/05_ml05_perf_meas.rmd
          - text: "06 Explaining Black-Box Models With LIME"
            file: content/01_journal/06_ml06_lime.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto